"""Bundled StandardFirmata firmware images.

Holds the prebuilt StandardFirmata Intel HEX files and a ``manifest.json`` that
maps each board id to its firmware image. These are generated by
``scripts/build_firmware.py`` (``make firmware``) and shipped with the package so
``liveduino-cli flash`` works offline, without the Arduino IDE.
"""
